# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3f38a42b74df162c873301f3601a7ef5"
name = "SmartFormly"
application_url = "https://smartformly.kaswebtechsolutions.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_script_tags,write_script_tags"

[auth]
redirect_urls = [ "https://smartformly.kaswebtechsolutions.com/api/auth" ]
