# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8077e7ea8b4019ea709f16552d40d310"
name = "BUNDLE KIT"
application_url = "https://bundlekit.kaswebtechsolutions.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/delete"
  topics = [ "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/discounts/delete"
  topics = ["discounts/delete"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,read_fulfillments,read_inventory,read_order_edits,read_orders,read_products,write_discounts,write_draft_orders,write_fulfillments,write_inventory,write_order_edits,write_orders,write_products"

[auth]
redirect_urls = [ "https://bundlekit.kaswebtechsolutions.com/api/auth" ]

[app_proxy]
url = "https://bundlekit.kaswebtechsolutions.com"
subpath = "bundler"
prefix = "apps"
